### ISSUE TITLE
TLS 1.3

### ISSUE THREAD

**Issue by ghost** [fedosgad/mirror_proxy#1]
Does this support TLS 1.3? it seems it's based on uTLS which is based on crypto/TLS which claims to only partially implement TLS 1.2

**Comment by fedosgad** [comment]
As per [docs](https://pkg.go.dev/crypto/tls), TLS 1.3 is implemented in crypto/tls. AFAIK, named groups are limited to elliptic curves, and not all TLS 1.3 features are implemented (not sure about early data).

From my experience, TLS 1.3 works well enough. If you can confirm the opposite - please write back.

**Comment by ghost** [comment]
Indeed I also found that page later. Completely new to Golang so still exploring. Thanks for confirming!

>  and not all TLS 1.3 features are implemented (not sure about early data).

Where in the code are these error cases handled? Going through your code base right now

To add support for these missing TLS 1.3 I would have to fork uTLS right?

**Comment by fedosgad** [comment]
Yes, all actual TLS functionality is inside utls. This program is only a thin wrapper around it and go-proxy, which handles client connections and fingerprinting.

**Comment by fedosgad** [comment]
Closing this. If you have other questions regarding TLS 1.3, feel free to re-open.
