### ISSUE TITLE
SSL_ERROR_INTERNAL_ERROR_ALERT

### ISSUE THREAD

**Issue by chribro88** [fedosgad/mirror_proxy#4]
Having this SSL_ERROR_INTERNAL_ERROR_ALERT error occurring resulting in the browser page not loading. The page is open for a sometime with new requests coming in periodically, but eventually this error will happen and crash the page.

Browser is Firefox which is connected to Mirror Proxy (http). The request is HTTPS.
Mirror Proxy is configured to use an Upstream Proxy (HTTP) which is HAProxy  (set up as a forward proxy). There are no errors in HAProxy that I can see.

Mirror proxy has the following errors I can see:
```
2023/03/10 06:47:08 [221] INFO: Client ALPN offers: [h2 http/1.1]
2023/03/10 06:47:08 [221] INFO: Client hello fingerprinting error unsupported extension PreSharedKey
2023/03/10 06:47:09 [221] INFO: Remote conn established
2023/03/10 06:47:09 [221] INFO: Wait for extractALPN
2023/03/10 06:47:09 [221] INFO: Closing remotePlaintextConn
2023/03/10 06:47:09 [221] WARN: Couldn't connect: error extracting ALPN: unsupported extension PreSharedKey
```
which seem to occur here:
[utls.go L248](https://github.com/fedosgad/mirror_proxy/blob/master/hijackers/utls.go#L248)

and here, respectively:
[utls.go L117](https://github.com/fedosgad/mirror_proxy/blob/master/hijackers/utls.go#L117)
[tls_hijacker.go L27](https://github.com/fedosgad/mirror_proxy/blob/a23128341e249941ac2d88a389834d9669a40480/tls_hijacker.go#L27)

Looks like there's a recent commit of utls.fingerprinter which removes KeepPSK. It looks like previously if KeepPSK was set to `false`, it would throw the err 'unsupported PreSharedKey'. ~~I tried changing it to `true` here in [utls.go](https://github.com/fedosgad/mirror_proxy/blob/master/hijackers/utls.go#L242) but didn't seem to fix anything..~~ 
Actually I don't it compiled with KeepPSK to `true` - so testing that now. Though I thought I read on the utls git that it messes with the TLS fingerprint...

Definitely a few moving parts and I haven't got any real way to reproduce the error (or whether its even a Mirror Proxy problem) but just wanted to check if this was something that had been come across whilst using Mirror Proxy?

Edit: Tried 1.3.0 utls, error was then `WARN: Couldn't connect: remote error: tls: error decoding message`.

**Comment by fedosgad** [comment]
Hello and sorry for late answer!

I have seen the error you describe too. It indeed appears when ClientHello contains PreSharedKey extension. I have set `KeepPSK` to `false` deliberately. If ClientHello contains non-empty PSK extension, it means that client and server have already established their encryption key(s) and now want to reuse them. If PSK extension is passed as is, mirror_proxy would not be able to decrypt traffic (which is main purpose of this tool). Correct me if I am wrong, but I think there is no way for mirror_proxy (or any MITM proxy in general) to decrypt TLS traffic with previously established keys without omitting PSK extension from initial ClientHello.

Also, thanks for pointing that utls 1.3.0 deprecates `KeepPSK`! I will look into their changes for suitable alternative.

**Comment by fedosgad** [comment]
Closing (wontfix).
